### ISSUE TITLE
Naming convention for test packages

### ISSUE THREAD

**Issue by walterxie** [bioDS/beast_phylonco#3]
The test classes should be the same naming spaces with the classes being tested:

https://softwareengineering.stackexchange.com/questions/328780/naming-convention-for-test-packages

In the Intellij, the tests folder should be tagged as "Tests" (green) :

<img width="1328" alt="intellij" src="https://user-images.githubusercontent.com/5743014/124040330-d1fe1900-da58-11eb-9fbe-3a85b43a9089.png">

**Comment by walterxie** [comment]
@kche309 please correct your tests package naming, for example:
`BinaryErrorModelTest` is testing `phylonco.beast.evolution.errormodel.BinaryErrorModel`, which should be in `phylonco.beast.evolution.errormodel.`

**Comment by kche309** [comment]
@walterxie I can move the test classes to the phylonco namespace. 

Do you mean having the package path `package a.b.c` the same as the main class if the main class is in `a.b.c.MainClass`?

I was following the test package naming convention from beast2 

https://github.com/CompEvol/beast2/blob/master/src/test/beast/evolution/substmodel/HKYTest.java

In the HKYTest.java the package name is `package test.beast.evolution.substmodel;` to test `beast.evolution.substitutionmodel.HKY`

**Comment by walterxie** [comment]
I see, then it is up to you to use one of the conventions. One example of LPhy tests is:

https://github.com/LinguaPhylo/linguaPhylo/blob/master/LPhy/test/lphy/evolution/coalescent/StructuredCoalescentTest.java

**Comment by J-Moravec** [comment]
I have noticed that many beast packages have a similar problem. Perhaps it is an opportunity to specify this in Beast dev. documentation?

**Comment by walterxie** [comment]
I did not complete the changes of package naming in tests. But they are working based on the project structure (screen shot above), except of `DataTypeDeEncodeTest.testStringToEncoding` failed:

<img width="1286" alt="Screen Shot 2021-07-01 at 11 48 17 AM" src="https://user-images.githubusercontent.com/5743014/124044756-3d001d80-da62-11eb-9fde-4c1580ebc393.png">

**Comment by kche309** [comment]
@walterxie Thanks for the example. I'll restructure the test classes to follow the Lphy convention. I think this is the better way to do this. 

The test classes will also be moved to `test/` outside of the `src/` directory. 

I think initially the test classes were structured like Lphy, but we switched to follow beast2 convention some time in between.

**Comment by kche309** [comment]
@walterxie The `DataTypeDeEncodeTest.testStringToEncoding` failed because of the merge. I'll make a commit to fix this.

**Comment by kche309** [comment]
@walterxie I have refactored the test classes to use the correct naming convention, see commit https://github.com/bioDS/beast_phylonco/commit/48515577582edd4067e510472c8f48e305b22b5f.
